### ISSUE TITLE
Can not connect to Spotify

### ISSUE THREAD

**Issue by AlecWiese** [iKenndac/Viva#1]
Downloaded the latest snapshot build, as of January 18th 2012 7:05pm central time. I have a Spotify premium account and I'm running Mac OSX 10.7.2. But when I try and log in it pops up "Can not connect to Spotify". Sorry if thats not very detailed but thats all that happens

**Comment by iKenndac** [comment]
Hi,

The core connectivity is based on libspotify, which has been working fine for months and months. Please check your connectivity and firewalls.

**Comment by AlecWiese** [comment]
Alright I'll do some double checking of my firewall settings and try and stop by a friends to see if I can get it to connect there
