### ISSUE TITLE
Can't login through facebook

### ISSUE THREAD

**Issue by kilianc** [iKenndac/Viva#13]
I don't even have a password :(

**Comment by iKenndac** [comment]
You need to use the official desktop client to sign up first. Once you have (and you have a Premium account), you should be able to sign in with your Facebook username and password.

**Comment by kilianc** [comment]
I did, in fact I said login, not signup.
I already have my spotify premium account, and I log in with my facebook email and password.

Viva tells me: Can not connect to spotify.  

## 

Kilian C.

**Comment by iKenndac** [comment]
Ok, I'll have a look. What does "I don't even have a password" mean?

**Comment by kilianc** [comment]
I meant, a spotify password, because I signin with facebook ;)
Thanks for your time!

## 

Kilian C.
