### ISSUE TITLE
Change Spotify BPM Swift

### ISSUE THREAD

**Issue by ghost** [iKenndac/Viva#16]
Hello iKenndac,
I  am developing an iPhone application with integrating Spotify SDK. Is there any way I can download the Spotify song through any Spotify Api or any other way because I developing a music application which change the song bpm (Beats Per Minutes). But I can’t change Spotify song bpm because Spotify song play online through Spotify methods with the Spotify premium account. So any way to download Spotify song. Come to main point i want to download song or any alternative way to change BPM of song? Could you please suggest  a way ASAP.

**Comment by iKenndac** [comment]
This has nothing to do with this project. You should contact Spotify Developer Support.
