### ISSUE TITLE
AirPlay support

### ISSUE THREAD

**Issue by slowmove** [iKenndac/Viva#7]
The possibility to choose an AirPlay device, such as an Airport Express, as receiver for the outgoing sound.

**Comment by iKenndac** [comment]
Low priority until someone can convince me why I need to spend the effort on this while AirFoil exists (that isn't "I don't want to pay for AirFoil").

**Comment by slowmove** [comment]
This can be closed since Mac OS X 10.8 Mountain Lion will have AirPlay built-in

**Comment by herrernst** [comment]
I know that it is possible to use Airplay as a global audio output device on OS X 10.8. But it still would be great if you just could reroute Spotify's audio to Airplay (to keep sound from other apps local).

**Comment by herrernst** [comment]
On OS X 10.8, using AirPlay is just like switching sound output.
Just for my personal purpose, I have changed Viva to output to AirPlay, if a device is found: https://github.com/herrernst/Viva/commit/b3ca48bd0d2d5679b77ddafac40940e331e67b91
If properly implemented, there should be a sound output device chooser of course.
