### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by loretoparisi** [iKenndac/Viva#9]
Since last commit,
I'm not able to compile anymore the client. I have a lot of errors like that

Cannot find interface declaration for 'SPCoreAudioController', superclass of 'EQCoreAudioController'; did you mean 'EQCoreAudioController'?
Trying to recursively use 'SPCoreAudioController' as superclass of 'EQCoreAudioController'
Cannot find protocol declaration for 'SPCoreAudioControllerDelegate'
Property 'volume' not found on object of type 'EQCoreAudioController *'

There are also several problems with ARC...

No visible @interface for 'SPSession' declares the selector 'beginLogout:'
No visible @interface for 'SPSession' declares the selector 'trackForURL:callback:'

Thanks for your work, I tested out the Viva client when I was able to compile it and it's a useful source for ideas.

**Comment by iKenndac** [comment]
Make sure you do a `git submodule update` in the Viva repo and are using Xcode 4.3+.

**Comment by loretoparisi** [comment]
I see,
after updated the submodules I have just these two

'stream_decoder.h' file not found
in
/Users/loretoparisi/Projects/COCOA/Viva/Viva/VivaFLACDecoderWorker.m

and
/Users/loretoparisi/Projects/COCOA/Viva/Viva/LocalFileSource+LocalFileSourceFLACAdditions.m

[UPDATE]
I just found out that the FLAC library libFLAC.a in Frameworks/flac is missing.

**Comment by iKenndac** [comment]
`git submodule update --init`

This is all covered in the README — please read through that (specifically the "Building" section) before opening tickets on building problems.

**Comment by loretoparisi** [comment]
Thanks a lot. Everything it's ok now.
